"""autogenerated by genpy from rl_msgs/RLExperimentInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RLExperimentInfo(genpy.Message):
  _md5sum = "df389dab0f017dc2a66e6cedd44b7a1e"
  _type = "rl_msgs/RLExperimentInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Message displaying / plotting / printing info about experiments

int32 episode_number
float32 episode_reward

int32 number_actions

"""
  __slots__ = ['episode_number','episode_reward','number_actions']
  _slot_types = ['int32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       episode_number,episode_reward,number_actions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RLExperimentInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.episode_number is None:
        self.episode_number = 0
      if self.episode_reward is None:
        self.episode_reward = 0.
      if self.number_actions is None:
        self.number_actions = 0
    else:
      self.episode_number = 0
      self.episode_reward = 0.
      self.number_actions = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_ifi.pack(_x.episode_number, _x.episode_reward, _x.number_actions))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.episode_number, _x.episode_reward, _x.number_actions,) = _struct_ifi.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_ifi.pack(_x.episode_number, _x.episode_reward, _x.number_actions))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.episode_number, _x.episode_reward, _x.number_actions,) = _struct_ifi.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_ifi = struct.Struct("<ifi")
